  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: trivy_fs

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bankapp-target
          path: bankapp/target

      - name: SonarQube Scan
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=bankapp \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: "Show Quality Gate Status"
        run: echo "Quality Gate: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
