name: bankapp-devsecops-pipeline

on:
  push:
    branches: [" * "]
  pull_request:
    branches: ["* " ]
# Security: restrict default permissions to read-only
permissions:
  contents: read
jobs:
 # 1 Trivy File System Scan
  trivy_fs_scan:
    name: trivy_fs_scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bankapp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@0.24.0

   # 2 compile
  compile:
    name: compile_project
    runs-on: ubuntu-latest
    needs: trivy_fs_scan
    defaults:
      run:
        working-directory: bankapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Compile
        run: mvn -B compile

  # 4️⃣ Unit Tests
# ------------------------------------------------
  unit_tests:
    name: unit_tests
    runs-on: ubuntu-latest
    needs: compile

    defaults:
      run:
        working-directory: bankapp

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run tests
        run: mvn test

        
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
