name: bankapp-devsecops-pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:

  # 1️⃣ Compile
  compile:
    name: Compile
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bankapp
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Compile
        run: mvn -B compile

      - name: Package
        run: mvn -B package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bankapp-target
          path: bankapp/target/*.jar

  # 2️⃣ Test
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: compile
    defaults:
      run:
        working-directory: bankapp

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run tests
        run: mvn test

  # 3️⃣ Trivy File System Scan
  trivy_fs:
    name: Trivy File System Scan
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: bankapp

    steps:
      - uses: actions/checkout@v4

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH

  # 4️⃣ SonarQube Analysis
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: trivy_fs

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bankapp-target
          path: ./artifact

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: SonarQube Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=bankapp \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  # 5️⃣ Quality Gate Check
  quality_gate:
    name: Quality Gate Check
    runs-on: ubuntu-latest
    needs: sonar

    steps:
      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        with:
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

 

      - name: Build Docker Image
        run: |
          docker build -t bankapp:latest .
